app:
  proxy.pool:
    url: http://192.168.3.117:5000/get/
    urls: http://192.168.3.117:5000/get_all/
    ips:
      - 120.26.162.31:3333
      - 118.31.238.185:3333
      - 114.55.24.150:3333
      - 121.199.48.108:3333
      - 120.26.82.81:3333
      - 121.199.14.53:3333
      - 118.123.173.83:3333
      - 118.123.173.84:3333
      - 119.6.202.170:9999
      - 119.6.202.172:9999
      - 119.6.202.173:9999
  html.template:
    table: <table><tbody><tr><td align="center" rowspan="1" colspan="2"><div><h4>bulletinName </h4></div></td></tr><tr><td align="right" colspan="2"><div>发布日期：bulletinssueTime&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div></td></tr><tr><td class="even"><p>所属行业：<span>industriesType</span></p></td><td><p>所属地区：<span>regionCode</span></p></td></tr><tr><td class="even"><p>招标项目建立时间：<span>createTime</span></p></td><td><p><span></span></p></td></tr><tr><td class="even"><p>招标代理机构代码：<span title="">tenderAgencyCodevalue</span></p></td><td><p>招标代理机构名称：<span title="tenderAgencyName">tenderAgencyName</span></p></td></tr><tr><td class="even"><p>招标人名称：<span title="tendererName">tendererName</span></p></td><td><p>招标组织方式：<span>tenderOrganizeForm</span></p></td></tr><tr><td class="even"><p>行政监督部门代码：<span>superviseDeptCodevalue</span></p></td><td><p>行政监督部门名称：<span>superviseDeptNamevalue</span></p></td></tr><tr><td class="even"><p>行政审核部门代码：<span>approveDeptCodevalue</span></p></td><td><p>行政审核部门名称：<span>approveDeptNamevalue</span></p></td></tr><tr><td rowspan="1" colspan="2"><div ><h5>招标内容与范围及招标方案说明：</h5><span>bulletinContent</span></td></tr></tbody></table>
    announcement: <table><tbody><tr><td>{bulletinName}</td></tr><tr><td>{bulletinssueTime}</td></tr><tr><td>{transactionPlatfCode}</td></tr><tr><td>{tenderProjectCode}</td></tr><tr><td>{formatContent}</td></tr></tbody></table>
    bidOpen: <div class="openCloseWrap"><div class="title fix open"><h4 class="fleft">{openBidRecordName}</h4><div class="ocBtn fright"></div></div><div>{transactionPlatfCode}</div><div>{bidSectionCodes}</div><div class="inner"><div >开标时间：{bidOpeningTime}&nbsp;&nbsp;</div><table class="table_1" border="0" bordercolor="#999"><tbody><tr><td colspan="3" style="text-align:left;"></td></tr><tr><td>投标人名称</td><td>投标报价</td><td>交货期</td></tr>{formatContent}</tbody></table></div></div>