logging:
  level:
    com.har.sjfxpt.crawler.ggzy: info
    us.codecraft.webmagic.downloader: error

spring:
  data:
    mongodb:
      uri: mongodb://192.168.3.108:27017/ggzy
  redis:
      host: 192.168.3.81
      port: 6379
      password: har123
      database: 0

hbase.zookeeper.quorum: s97,s98,s99
hbase.table.clean: false
hbase.table.namespace: bid_news_test

app.proxy.pool:
  url: http://192.168.3.117:5000/get/
  urls: http://192.168.3.117:5000/get_all/
  ips:
    - 120.26.162.31:3333