logging:
  level:
    com.har.sjfxpt.crawler.ggzy: info
    us.codecraft.webmagic.downloader: error
    com.har.sjfxpt.crawler.ccgp.ZhengFuCaiGouDownloader: warn
  file: app.log

spring:
  data:
    mongodb:
      uri: mongodb://business:business123@192.168.3.95:27017/business
    redis:
      repositories:
        enabled: false
  redis:
      host: 192.168.3.108
      port: 6379
      password: 123456
      database: 14
  profiles:
    include: conf

hbase.zookeeper.quorum: s94,s95,s96
hbase.table.clean: false
hbase.table.namespace: bid_news

app.fetch.current.day: true